# DigitalOcean Playbook
---
- name: DigitalOcean
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:

  - name: Include the variables for droplet creation
    include_vars: vars/droplet.yml

  - name: Obtain droplet info
    digital_ocean:
      name: "{{ droplet_name }}"
      api_token: "{{ digital_ocean_api_token }}"
      unique_name: yes
      wait_timeout: 500
    register: droplet_info

  - name: Remove droplet
    digital_ocean:
        api_token: "{{ digital_ocean_api_token }}"
        id: "{{ droplet_info.droplet.id }}"
        state: deleted


