# DigitalOcean Playbook
---
- name: DigitalOcean
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:

  - name: Include the variables for droplet creation
    include_vars: vars/droplet.yml

  - name: Remove current SSH key (to support use on different machines)
    digital_ocean_sshkey:
      state: absent
      name: "{{ ssh_key_name }}"
      ssh_pub_key: "{{ droplet_ssh_key }}"
      oauth_token: "{{ digital_ocean_api_token }}"

  - name: Ensure SSH key exists on DigitalOcean
    digital_ocean:
      state: present
      command: ssh
      name: "{{ ssh_key_name }}"
      ssh_pub_key: "{{ droplet_ssh_key }}"
      api_token: "{{ digital_ocean_api_token }}"
    register: do_ssh_key
  
  - name: Create Droplet
    digital_ocean:
      state: present
      command: droplet
      name: "{{ droplet_name }}"
      api_token: "{{ digital_ocean_api_token }}"
      size_id: "{{ droplet_size }}"
      region_id: "{{ droplet_region }}"
      image_id: "{{ droplet_image }}"
      ssh_key_ids: "{{ do_ssh_key.ssh_key.id }}"
      unique_name: yes
      wait_timeout: 500
    register: droplet_info

  - name: Add new instance to host group
    add_host: hostname={{ droplet_info.droplet.ip_address }} groupname=digital_ocean_droplet

  - name: Wait for SSH to come up
    wait_for: host={{ droplet_info.droplet.ip_address }} port=22 delay=10 timeout=60 state=started

- name: Configure manticore instance
  hosts: digital_ocean_droplet
  remote_user: root
  gather_facts: False

  tasks:

    - name: include ansible / manticore vars
      include_vars: vars/ansible.yml
    
    - name: Create a user with sudo privileges
      user:
        name: "{{ remote_uname }}"
        state: present
        shell: /bin/bash
        groups: sudo

    - name: Set authorized key with id_rsa.pub home file
      authorized_key:
        user: "{{ remote_uname }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

    - name: Allow run commands as root with dropletuser
      shell: "echo '%sudo ALL=NOPASSWD: ALL' >> /etc/sudoers"
    
    - name: Install pip on remote droplet
      apt:
        name: python3-pip 
        state: present
        update_cache: yes

    - name: Install manticore on remote droplet
      pip: 
        name: manticore[native]

    - name: Copy cwd to remote droplet
      become: yes
      become_user: "{{ remote_uname }}"
      synchronize: 
        src: "./"
        dest: "/home/{{ remote_uname }}/"
        dirs: yes
        mode: push
        rsync_opts:
            - "--exclude=.git/"

    - name: Run target script asynchronously
      become: yes
      become_user: "{{ remote_uname }}"
      shell: |
        cd "/home/{{ remote_uname }}/{{ manticore_env }}"
        python3 "{{ manticore_script }}"
      register: log_output

    - name: Save logs
      local_action: copy content={{ log_output }} dest={{ logfile }}

    - name: Fetch manticore results from remote server
      synchronize:
        rsync_path: "sudo rsync"
        mode: pull
        src:  "/home/{{ remote_uname }}/{{ manticore_env }}/."
        dest: "{{ manticore_env }}/"
        recursive: yes
