# DigitalOcean Info Playbook
---
- name: DigitalOcean
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

  - name: Include variables
    include_vars: vars/droplet.yml

  - name: Reset SSH key
    digital_ocean_sshkey:
      state: absent
      ssh_pub_key: "{{ droplet_ssh_key }}"
      oauth_token: "{{ digital_ocean_api_token }}"

  - name: Obtain SSH id
    digital_ocean:
      state: absent
      command: ssh
      name: "{{ ansible_user_id }}"
      ssh_pub_key: "{{ droplet_ssh_key }}"
      api_token: "{{ digital_ocean_api_token }}"
